services:
  mongodb:
    image : mongo
    container_name: mongodb
    # volumes:
    #   - ./mongodb/data:/data/db
    ports:
      - 27017:27017
    restart: unless-stopped

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: app
    ports:
      - 5000:5000
    restart: unless-stopped
    depends_on:
      - mongodb